@startuml DriveHub

title DriveHub

class Vehiculo{
    #numeroMatricula
    #estado
    #tarifaBase
    #cargo
    +settersGetters()
}
class Compacto extends Vehiculo{}
class Sedan extends Vehiculo{}
class Suv extends Vehiculo{}

class Cliente{
    #nombre
    +settersGetters()
}


@enduml